---
# Copyright (c) 2025 The Regents of the University of California
# SPDX-License-Identifier: BSD-3-Clause

name: CI Tests for Pull Requests

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
    cancel-in-progress: true

jobs:
    pre-commit:
        runs-on: ubuntu-24.04
        if: github.event.pull_request.draft == false
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'

            - name: Run pre-commit hooks
              uses: pre-commit/action@v3.0.1


    unit-tests:
        runs-on: ubuntu-24.04

        if: github.event.pull_request.draft == false
        needs: pre-commit

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ];
                  then
                    pip install -r requirements.txt
                  fi

            - name: Install Azure Functions Core Tools
              run: |
                  curl https://packages.microsoft.com/keys/microsoft.asc | \
                    gpg --dearmor > microsoft.gpg
                  sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
                  sudo sh -c \
                    'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" \
                    > /etc/apt/sources.list.d/dotnetdev.list'
                  sudo apt-get update
                  sudo apt-get install azure-functions-core-tools-4

            - name: Start Azure Functions
              run: |
                  # Start Azure Functions in the background
                  func start --port 7071 --no-build &
                  # Wait for the functions to be ready (adjust time as needed)
                  sleep 20

            - name: Run tests
              run: |
                  python3 -m unittest tests.resources_api_unit_tests -v
